### ISSUE TITLE
how to get the catima sync ?

### ISSUE THREAD

**Issue by aspx1981** [CatimaLoyalty/Sync#9]
Hello,
how can I get the Catima Sync server and build it ?

Thanks

**Comment by TheLastProject** [comment]
There's no way to get it, no sync code has been written yet. People have shown interest in helping with this and then nothing happened and I don't have the time to do it all by myself :(

**Comment by aspx1981** [comment]
thanks for your answer, I'd like to help but unfortunately I don't have the knowledge.
I think this app and server should be very similar to Passbolt CE, just instead of storing/showing passwords and share them, do it with barcode and QR code.
